import { describe, expect, it } from 'bun:test';

import { indexTelegramMessagesById } from './messageIndexer';
import { TelegramMessage } from './types';

describe('messageIndexer', () => {
    describe('indexTelegramMessagesById', () => {
        it('should handle message service type', () => {
            const actual = indexTelegramMessagesById([
                {
                    action: {
                        chatId: '1234',
                        className: 'MessageActionChannelMigrateFrom',
                        title: 'IM',
                    },
                    className: 'MessageService',
                    date: 133,
                    flags: 2,
                    fromId: null,
                    id: 1,
                    legacy: false,
                    mediaUnread: false,
                    mentioned: false,
                    out: true,
                    peerId: {
                        channelId: '556',
                        className: 'PeerChannel',
                    },
                    post: false,
                    reactions: null,
                    reactionsArePossible: false,
                    replyTo: null,
                    silent: false,
                    ttlPeriod: null,
                } as unknown as TelegramMessage,
            ]);

            expect(actual).toEqual({
                1: {
                    className: 'MessageService',
                    date: 133,
                    id: 1,
                },
            });
        });

        it('should handle flat group irrelevant message from admin', () => {
            const actual = indexTelegramMessagesById([
                {
                    className: 'Message',
                    date: 18,
                    editDate: null,
                    editHide: false,
                    effect: null,
                    entities: [
                        {
                            className: 'MessageEntityBotCommand',
                            length: 19,
                            offset: 0,
                        },
                    ],
                    factcheck: null,
                    flags: 8388994,
                    flags2: 0,
                    forwards: null,
                    fromBoostsApplied: null,
                    fromId: {
                        className: 'PeerUser',
                        userId: '33',
                    },
                    fromScheduled: false,
                    fwdFrom: null,
                    groupedId: null,
                    id: 4,
                    invertMedia: false,
                    legacy: false,
                    media: null,
                    mediaUnread: false,
                    mentioned: false,
                    message: 'ewwo',
                    noforwards: false,
                    offline: false,
                    out: true,
                    peerId: {
                        channelId: '55',
                        className: 'PeerChannel',
                    },
                    pinned: false,
                    post: false,
                    postAuthor: null,
                    quickReplyShortcutId: null,
                    reactions: null,
                    replies: {
                        channelId: null,
                        className: 'MessageReplies',
                        comments: false,
                        flags: 4,
                        maxId: 5,
                        readMaxId: null,
                        recentRepliers: null,
                        replies: 1,
                        repliesPts: 4245,
                    },
                    replyMarkup: null,
                    replyTo: null,
                    reportDeliveryUntilDate: null,
                    restrictionReason: null,
                    savedPeerId: null,
                    silent: false,
                    ttlPeriod: null,
                    viaBotId: null,
                    viaBusinessBotId: null,
                    videoProcessingPending: false,
                    views: null,
                } as unknown as TelegramMessage,
            ]);

            expect(actual).toEqual({
                4: {
                    className: 'Message',
                    date: 18,
                    fromId: {
                        userId: '33',
                    },
                    id: 4,
                    message: 'ewwo',
                },
            });
        });

        it('should handle flat group message from a bot', () => {
            const actual = indexTelegramMessagesById([
                {
                    className: 'Message',
                    date: 15,
                    editDate: null,
                    editHide: false,
                    effect: null,
                    entities: [
                        {
                            className: 'MessageEntityCode',
                            length: 14,
                            offset: 23,
                        },
                    ],
                    factcheck: null,
                    flags: 408,
                    flags2: 0,
                    forwards: null,
                    fromBoostsApplied: null,
                    fromId: {
                        className: 'PeerUser',
                        userId: '10',
                    },
                    fromScheduled: false,
                    fwdFrom: null,
                    groupedId: null,
                    id: 5,
                    invertMedia: false,
                    legacy: false,
                    media: null,
                    mediaUnread: false,
                    mentioned: true,
                    message: 'X',
                    noforwards: false,
                    offline: false,
                    out: false,
                    peerId: {
                        channelId: '1395453223',
                        className: 'PeerChannel',
                    },
                    pinned: false,
                    post: false,
                    postAuthor: null,
                    quickReplyShortcutId: null,
                    reactions: null,
                    replies: null,
                    replyMarkup: null,
                    replyTo: {
                        className: 'MessageReplyHeader',
                        flags: 16,
                        forumTopic: false,
                        quote: false,
                        quoteEntities: null,
                        quoteOffset: null,
                        quoteText: null,
                        replyFrom: null,
                        replyMedia: null,
                        replyToMsgId: 4,
                        replyToPeerId: null,
                        replyToScheduled: false,
                        replyToTopId: null,
                    },
                    reportDeliveryUntilDate: null,
                    restrictionReason: null,
                    savedPeerId: null,
                    silent: false,
                    ttlPeriod: null,
                    viaBotId: null,
                    viaBusinessBotId: null,
                    videoProcessingPending: false,
                    views: null,
                } as unknown as TelegramMessage,
            ]);

            expect(actual).toEqual({
                5: {
                    className: 'Message',
                    date: 15,
                    fromId: {
                        userId: '10',
                    },
                    id: 5,
                    message: 'X',
                    replyTo: {
                        replyToMsgId: 4,
                    },
                },
            });
        });

        it('should handle message from user with a private profile', () => {
            const actual = indexTelegramMessagesById([
                {
                    className: 'Message',
                    date: 16,
                    editDate: null,
                    editHide: false,
                    effect: null,
                    entities: null,
                    factcheck: null,
                    flags: 8388868,
                    flags2: 0,
                    forwards: null,
                    fromBoostsApplied: null,
                    fromId: {
                        className: 'PeerUser',
                        userId: '11',
                    },
                    fromScheduled: false,
                    fwdFrom: {
                        channelPost: null,
                        className: 'MessageFwdHeader',
                        date: 1682956105,
                        flags: 32,
                        fromId: null,
                        fromName: '.',
                        imported: false,
                        postAuthor: null,
                        psaType: null,
                        savedDate: null,
                        savedFromId: null,
                        savedFromMsgId: null,
                        savedFromName: null,
                        savedFromPeer: null,
                        savedOut: false,
                    },
                    groupedId: null,
                    id: 6,
                    invertMedia: false,
                    legacy: false,
                    media: null,
                    mediaUnread: false,
                    mentioned: false,
                    message: 'H',
                    noforwards: false,
                    offline: false,
                    out: false,
                    peerId: {
                        channelId: '111',
                        className: 'PeerChannel',
                    },
                    pinned: false,
                    post: false,
                    postAuthor: null,
                    quickReplyShortcutId: null,
                    reactions: null,
                    replies: {
                        channelId: null,
                        className: 'MessageReplies',
                        comments: false,
                        flags: 0,
                        maxId: null,
                        readMaxId: null,
                        recentRepliers: null,
                        replies: 0,
                        repliesPts: 4245,
                    },
                    replyMarkup: null,
                    replyTo: null,
                    reportDeliveryUntilDate: null,
                    restrictionReason: null,
                    savedPeerId: null,
                    silent: false,
                    ttlPeriod: null,
                    viaBotId: null,
                    viaBusinessBotId: null,
                    videoProcessingPending: false,
                    views: null,
                } as unknown as TelegramMessage,
            ]);

            expect(actual).toEqual({
                6: {
                    className: 'Message',
                    date: 16,
                    fromId: {
                        userId: '11',
                    },
                    fwdFrom: {
                        fromName: '.',
                    },
                    id: 6,
                    message: 'H',
                },
            });
        });

        it('should handle message service action from admin', () => {
            const actual = indexTelegramMessagesById([
                {
                    action: {
                        className: 'MessageActionChatDeleteUser',
                        userId: '11',
                    },
                    className: 'MessageService',
                    date: 66,
                    flags: 770,
                    fromId: {
                        className: 'PeerUser',
                        userId: '33',
                    },
                    id: 7,
                    legacy: false,
                    mediaUnread: false,
                    mentioned: false,
                    out: true,
                    peerId: {
                        channelId: '1395453223',
                        className: 'PeerChannel',
                    },
                    post: false,
                    reactions: null,
                    reactionsArePossible: true,
                    replyTo: null,
                    silent: false,
                    ttlPeriod: null,
                } as unknown as TelegramMessage,
            ]);

            expect(actual).toEqual({
                7: {
                    className: 'MessageService',
                    date: 66,
                    fromId: {
                        userId: '33',
                    },
                    id: 7,
                },
            });
        });

        it('should handle message forwarded by bot from user', () => {
            const actual = indexTelegramMessagesById([
                {
                    className: 'Message',
                    date: 16,
                    editDate: null,
                    editHide: false,
                    effect: null,
                    entities: null,
                    factcheck: null,
                    flags: 8388868,
                    flags2: 0,
                    forwards: null,
                    fromBoostsApplied: null,
                    fromId: {
                        className: 'PeerUser',
                        userId: '4',
                    },
                    fromScheduled: false,
                    fwdFrom: {
                        channelPost: null,
                        className: 'MessageFwdHeader',
                        date: 1682956650,
                        flags: 1,
                        fromId: {
                            className: 'PeerUser',
                            userId: '45',
                        },
                        fromName: null,
                        imported: false,
                        postAuthor: null,
                        psaType: null,
                        savedDate: null,
                        savedFromId: null,
                        savedFromMsgId: null,
                        savedFromName: null,
                        savedFromPeer: null,
                        savedOut: false,
                    },
                    groupedId: null,
                    id: 9,
                    invertMedia: false,
                    legacy: false,
                    media: null,
                    mediaUnread: false,
                    mentioned: false,
                    message: 'A',
                    noforwards: false,
                    offline: false,
                    out: false,
                    peerId: {
                        channelId: '13',
                        className: 'PeerChannel',
                    },
                    pinned: false,
                    post: false,
                    postAuthor: null,
                    quickReplyShortcutId: null,
                    reactions: null,
                    replies: {
                        channelId: null,
                        className: 'MessageReplies',
                        comments: false,
                        flags: 4,
                        maxId: 13,
                        readMaxId: null,
                        recentRepliers: null,
                        replies: 2,
                        repliesPts: 4245,
                    },
                    replyMarkup: null,
                    replyTo: null,
                    reportDeliveryUntilDate: null,
                    restrictionReason: null,
                    savedPeerId: null,
                    silent: false,
                    ttlPeriod: null,
                    viaBotId: null,
                    viaBusinessBotId: null,
                    videoProcessingPending: false,
                    views: null,
                } as unknown as TelegramMessage,
            ]);

            expect(actual).toEqual({
                9: {
                    className: 'Message',
                    date: 16,
                    fromId: { userId: '4' },
                    fwdFrom: { fromId: { className: 'PeerUser', userId: '45' } },
                    id: 9,
                    message: 'A',
                },
            });
        });

        it('should handle admin reply to user message in flat group', () => {
            const actual = indexTelegramMessagesById([
                {
                    className: 'Message',
                    date: 18,
                    editDate: null,
                    editHide: false,
                    effect: null,
                    entities: null,
                    factcheck: null,
                    flags: 266,
                    flags2: 0,
                    forwards: null,
                    fromBoostsApplied: null,
                    fromId: {
                        className: 'PeerUser',
                        userId: '3',
                    },
                    fromScheduled: false,
                    fwdFrom: null,
                    groupedId: null,
                    id: 12,
                    invertMedia: false,
                    legacy: false,
                    media: null,
                    mediaUnread: false,
                    mentioned: false,
                    message: 'M',
                    noforwards: false,
                    offline: false,
                    out: true,
                    peerId: {
                        channelId: '13',
                        className: 'PeerChannel',
                    },
                    pinned: false,
                    post: false,
                    postAuthor: null,
                    quickReplyShortcutId: null,
                    reactions: null,
                    replies: null,
                    replyMarkup: null,
                    replyTo: {
                        className: 'MessageReplyHeader',
                        flags: 16,
                        forumTopic: false,
                        quote: false,
                        quoteEntities: null,
                        quoteOffset: null,
                        quoteText: null,
                        replyFrom: null,
                        replyMedia: null,
                        replyToMsgId: 9,
                        replyToPeerId: null,
                        replyToScheduled: false,
                        replyToTopId: null,
                    },
                    reportDeliveryUntilDate: null,
                    restrictionReason: null,
                    savedPeerId: null,
                    silent: false,
                    ttlPeriod: null,
                    viaBotId: null,
                    viaBusinessBotId: null,
                    videoProcessingPending: false,
                    views: null,
                } as unknown as TelegramMessage,
            ]);

            expect(actual).toEqual({
                12: {
                    className: 'Message',
                    date: 18,
                    fromId: { userId: '3' },
                    id: 12,
                    message: 'M',
                    replyTo: {
                        replyToMsgId: 9,
                    },
                },
            });
        });

        it('should handle bot acknowledgement in flat group', () => {
            const actual = indexTelegramMessagesById([
                {
                    className: 'Message',
                    date: 16,
                    editDate: null,
                    editHide: false,
                    effect: null,
                    entities: [
                        {
                            className: 'MessageEntityMention',
                            length: 11,
                            offset: 21,
                        },
                    ],
                    factcheck: null,
                    flags: 408,
                    flags2: 0,
                    forwards: null,
                    fromBoostsApplied: null,
                    fromId: {
                        className: 'PeerUser',
                        userId: '49',
                    },
                    fromScheduled: false,
                    fwdFrom: null,
                    groupedId: null,
                    id: 13,
                    invertMedia: false,
                    legacy: false,
                    media: null,
                    mediaUnread: false,
                    mentioned: true,
                    message: 'A',
                    noforwards: false,
                    offline: false,
                    out: false,
                    peerId: {
                        channelId: '13',
                        className: 'PeerChannel',
                    },
                    pinned: false,
                    post: false,
                    postAuthor: null,
                    quickReplyShortcutId: null,
                    reactions: null,
                    replies: null,
                    replyMarkup: null,
                    replyTo: {
                        className: 'MessageReplyHeader',
                        flags: 18,
                        forumTopic: false,
                        quote: false,
                        quoteEntities: null,
                        quoteOffset: null,
                        quoteText: null,
                        replyFrom: null,
                        replyMedia: null,
                        replyToMsgId: 12,
                        replyToPeerId: null,
                        replyToScheduled: false,
                        replyToTopId: 9,
                    },
                    reportDeliveryUntilDate: null,
                    restrictionReason: null,
                    savedPeerId: null,
                    silent: false,
                    ttlPeriod: null,
                    viaBotId: null,
                    viaBusinessBotId: null,
                    videoProcessingPending: false,
                    views: null,
                } as unknown as TelegramMessage,
            ]);

            expect(actual).toEqual({
                13: {
                    className: 'Message',
                    date: 16,
                    fromId: { userId: '49' },
                    id: 13,
                    message: 'A',
                    replyTo: {
                        replyToMsgId: 12,
                        replyToTopId: 9,
                    },
                },
            });
        });

        it('should handle message from user in a topic', () => {
            const actual = indexTelegramMessagesById([
                {
                    className: 'Message',
                    date: 17,
                    editDate: null,
                    editHide: false,
                    effect: null,
                    entities: null,
                    factcheck: null,
                    flags: 268,
                    flags2: 0,
                    forwards: null,
                    fromBoostsApplied: null,
                    fromId: {
                        className: 'PeerUser',
                        userId: '4',
                    },
                    fromScheduled: false,
                    fwdFrom: {
                        channelPost: null,
                        className: 'MessageFwdHeader',
                        date: 1741948302,
                        flags: 1,
                        fromId: {
                            className: 'PeerUser',
                            userId: '6',
                        },
                        fromName: null,
                        imported: false,
                        postAuthor: null,
                        psaType: null,
                        savedDate: null,
                        savedFromId: null,
                        savedFromMsgId: null,
                        savedFromName: null,
                        savedFromPeer: null,
                        savedOut: false,
                    },
                    groupedId: null,
                    id: 3907,
                    invertMedia: false,
                    legacy: false,
                    media: null,
                    mediaUnread: false,
                    mentioned: false,
                    message: 'M',
                    noforwards: false,
                    offline: false,
                    out: false,
                    peerId: {
                        channelId: '13',
                        className: 'PeerChannel',
                    },
                    pinned: false,
                    post: false,
                    postAuthor: null,
                    quickReplyShortcutId: null,
                    reactions: null,
                    replies: null,
                    replyMarkup: null,
                    replyTo: {
                        className: 'MessageReplyHeader',
                        flags: 24,
                        forumTopic: true,
                        quote: false,
                        quoteEntities: null,
                        quoteOffset: null,
                        quoteText: null,
                        replyFrom: null,
                        replyMedia: null,
                        replyToMsgId: 2961,
                        replyToPeerId: null,
                        replyToScheduled: false,
                        replyToTopId: null,
                    },
                    reportDeliveryUntilDate: null,
                    restrictionReason: null,
                    savedPeerId: null,
                    silent: false,
                    ttlPeriod: null,
                    viaBotId: null,
                    viaBusinessBotId: null,
                    videoProcessingPending: false,
                    views: null,
                } as unknown as TelegramMessage,
            ]);

            expect(actual).toEqual({
                3907: {
                    className: 'Message',
                    date: 17,
                    fromId: { userId: '4' },
                    fwdFrom: {
                        fromId: {
                            className: 'PeerUser',
                            userId: '6',
                        },
                    },
                    id: 3907,
                    message: 'M',
                    replyTo: {
                        forumTopic: true,
                        replyToMsgId: 2961,
                    },
                },
            });
        });

        it('should handle message reply from admin to user in topic', () => {
            const actual = indexTelegramMessagesById([
                {
                    className: 'Message',
                    date: 16,
                    editDate: null,
                    editHide: false,
                    effect: null,
                    entities: null,
                    factcheck: null,
                    flags: 266,
                    flags2: 0,
                    forwards: null,
                    fromBoostsApplied: null,
                    fromId: {
                        className: 'PeerUser',
                        userId: '3',
                    },
                    fromScheduled: false,
                    fwdFrom: null,
                    groupedId: null,
                    id: 3908,
                    invertMedia: false,
                    legacy: false,
                    media: null,
                    mediaUnread: false,
                    mentioned: false,
                    message: 'W',
                    noforwards: false,
                    offline: false,
                    out: true,
                    peerId: {
                        channelId: '11',
                        className: 'PeerChannel',
                    },
                    pinned: false,
                    post: false,
                    postAuthor: null,
                    quickReplyShortcutId: null,
                    reactions: null,
                    replies: null,
                    replyMarkup: null,
                    replyTo: {
                        className: 'MessageReplyHeader',
                        flags: 24,
                        forumTopic: true,
                        quote: false,
                        quoteEntities: null,
                        quoteOffset: null,
                        quoteText: null,
                        replyFrom: null,
                        replyMedia: null,
                        replyToMsgId: 2961,
                        replyToPeerId: null,
                        replyToScheduled: false,
                        replyToTopId: null,
                    },
                    reportDeliveryUntilDate: null,
                    restrictionReason: null,
                    savedPeerId: null,
                    silent: false,
                    ttlPeriod: null,
                    viaBotId: null,
                    viaBusinessBotId: null,
                    videoProcessingPending: false,
                    views: null,
                } as unknown as TelegramMessage,
            ]);

            expect(actual).toEqual({
                3908: {
                    className: 'Message',
                    date: 16,
                    fromId: { userId: '3' },
                    id: 3908,
                    message: 'W',
                    replyTo: {
                        forumTopic: true,
                        replyToMsgId: 2961,
                    },
                },
            });
        });

        it('should handle bot acknowledgement message in a topic', () => {
            const actual = indexTelegramMessagesById([
                {
                    className: 'Message',
                    date: 11,
                    editDate: null,
                    editHide: false,
                    effect: null,
                    entities: [
                        {
                            className: 'MessageEntityMention',
                            length: 7,
                            offset: 21,
                        },
                    ],
                    factcheck: null,
                    flags: 408,
                    flags2: 0,
                    forwards: null,
                    fromBoostsApplied: null,
                    fromId: {
                        className: 'PeerUser',
                        userId: '4',
                    },
                    fromScheduled: false,
                    fwdFrom: null,
                    groupedId: null,
                    id: 3909,
                    invertMedia: false,
                    legacy: false,
                    media: null,
                    mediaUnread: false,
                    mentioned: true,
                    message: 'R',
                    noforwards: false,
                    offline: false,
                    out: false,
                    peerId: {
                        channelId: '13',
                        className: 'PeerChannel',
                    },
                    pinned: false,
                    post: false,
                    postAuthor: null,
                    quickReplyShortcutId: null,
                    reactions: null,
                    replies: null,
                    replyMarkup: null,
                    replyTo: {
                        className: 'MessageReplyHeader',
                        flags: 26,
                        forumTopic: true,
                        quote: false,
                        quoteEntities: null,
                        quoteOffset: null,
                        quoteText: null,
                        replyFrom: null,
                        replyMedia: null,
                        replyToMsgId: 3908,
                        replyToPeerId: null,
                        replyToScheduled: false,
                        replyToTopId: 2961,
                    },
                    reportDeliveryUntilDate: null,
                    restrictionReason: null,
                    savedPeerId: null,
                    silent: false,
                    ttlPeriod: null,
                    viaBotId: null,
                    viaBusinessBotId: null,
                    videoProcessingPending: false,
                    views: null,
                } as unknown as TelegramMessage,
            ]);

            expect(actual).toEqual({
                3909: {
                    className: 'Message',
                    date: 11,
                    fromId: { userId: '4' },
                    id: 3909,
                    message: 'R',
                    replyTo: {
                        forumTopic: true,
                        replyToMsgId: 3908,
                        replyToTopId: 2961,
                    },
                },
            });
        });

        it('should handle message photo in a flat group', () => {
            const actual = indexTelegramMessagesById([
                {
                    className: 'Message',
                    date: 16,
                    editDate: null,
                    editHide: false,
                    effect: null,
                    entities: null,
                    factcheck: null,
                    flags: 8389380,
                    flags2: 0,
                    forwards: null,
                    fromBoostsApplied: null,
                    fromId: {
                        className: 'PeerUser',
                        userId: '4',
                    },
                    fromScheduled: false,
                    fwdFrom: {
                        channelPost: null,
                        className: 'MessageFwdHeader',
                        date: 1682958262,
                        flags: 1,
                        fromId: {
                            className: 'PeerUser',
                            userId: '45',
                        },
                        fromName: null,
                        imported: false,
                        postAuthor: null,
                        psaType: null,
                        savedDate: null,
                        savedFromId: null,
                        savedFromMsgId: null,
                        savedFromName: null,
                        savedFromPeer: null,
                        savedOut: false,
                    },
                    groupedId: null,
                    id: 15,
                    invertMedia: false,
                    legacy: false,
                    media: {
                        className: 'MessageMediaPhoto',
                        flags: 1,
                        photo: {
                            accessHash: '2378615023714951509',
                            className: 'Photo',
                            date: 1682958262,
                            dcId: 4,
                            fileReference: {
                                type: 'Buffer',
                            },
                            flags: 0,
                            hasStickers: false,
                            id: '55',
                            videoSizes: null,
                        },
                        spoiler: false,
                        ttlSeconds: null,
                    },
                    mediaUnread: false,
                    mentioned: false,
                    message: 'T',
                    noforwards: false,
                    offline: false,
                    out: false,
                    peerId: {
                        channelId: '13',
                        className: 'PeerChannel',
                    },
                    pinned: false,
                    post: false,
                    postAuthor: null,
                    quickReplyShortcutId: null,
                    reactions: null,
                    replies: {
                        channelId: null,
                        className: 'MessageReplies',
                        comments: false,
                        flags: 4,
                        maxId: 17,
                        readMaxId: null,
                        recentRepliers: null,
                        replies: 2,
                        repliesPts: 4245,
                    },
                    replyMarkup: null,
                    replyTo: null,
                    reportDeliveryUntilDate: null,
                    restrictionReason: null,
                    savedPeerId: null,
                    silent: false,
                    ttlPeriod: null,
                    viaBotId: null,
                    viaBusinessBotId: null,
                    videoProcessingPending: false,
                    views: null,
                } as unknown as TelegramMessage,
            ]);

            expect(actual).toEqual({
                15: {
                    className: 'Message',
                    date: 16,
                    fromId: { userId: '4' },
                    fwdFrom: {
                        fromId: {
                            className: 'PeerUser',
                            userId: '45',
                        },
                    },
                    id: 15,
                    media: { photo: { id: '55' } },
                    message: 'T',
                },
            });
        });
    });
});
